Update tt (2)
argument checker

diff --git a/Lab 04/tt b/Lab 04/tt
--- a/Lab 04/tt
+++ b/Lab 04/tt
@@ -16,3 +16,9 @@ user_guide() {
     echo "  tt view"
     echo "  tt clear"
 }
+
+if [ -z "$1" ]; then
+    echo "Invalid argument."
+    user_guide
+    exit 1
+fi
