Update tt
help function that displays the user guide or the invalid argument notification

diff --git a/Lab 04/tt b/Lab 04/tt
--- a/Lab 04/tt
+++ b/Lab 04/tt
@@ -63,3 +63,12 @@ case $1 in
             echo "Operation cancelled."
         fi
         ;;
+    help)
+        user_guide
+        ;;
+    *)
+        echo "Invalid argument."
+        user_guide
+        exit 1
+        ;;
+esac
